A = int(input("첫 번째 숫자를 입력하시오 :"))
B = int(input("두 번째 숫자를 입력하시오 :"))
print("두 수의 합 :" , A + B)
print("두 수의 차 :" , A - B)
print("두 수의 곱 :" , A * B)
print("두 수의 몫 :" , A // B)
print("두 수의 나머지 :" , A % B )