A = int(input("첫 번째 숫자를 입력하세요: "))
B = int(input("두 번째 숫자를 입력하세요: "))
result1 = A+B
result2 = A-B
result3 = A//B
result4 = A%B
result5= A*B
print(result1, end=' ')
print(result2, end=' ')
print(result3, end=' ')
print(result4, end=' ')
print(result5, end=' ')